# Generated by Django 4.0.7 on 2023-07-24 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fav',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='fav',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='fav',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='tags',
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Title must be greater than 2 characters')]),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Fav',
        ),
    ]
